"""Add total_questions column

Revision ID: 83b34acfa958
Revises: 
Create Date: 2025-07-09 15:16:02.135061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b34acfa958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=False))
        batch_op.drop_column('percentage')
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('percentage', sa.FLOAT(), nullable=False))
        batch_op.drop_column('total_questions')

    # ### end Alembic commands ###
